<a href="https://colab.research.google.com/github/anshita647/Learning_of_AI_and_ML/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array creation (array, arange, linspace, zeros, ones, eye)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#arange(start,stop,step)
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
#linspace(start, stop, num)
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr=np.zeros(5)#1D array zeros
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr=np.zeros((2,3))#2D array zeros
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones(4)#1D array ones
print(arr)

[1. 1. 1. 1.]


In [ ]:
arr=np.ones((3,2))#1D array ones
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing and Slicing

In [ ]:
#1D array
import numpy as np
arr=([2,3,5,9,10])
print(arr[3])
print(arr[-1])
#Positive index: counts from start (0,1,2...)
#Negative index: counts from end (-1,-2,-3...)

9
10


In [ ]:
#2D array
arr2d=[[1,2,3],
        [4,5,6],
        [7,8,9]]
print(arr2d[2][2])#row 2, column 2
print(arr2d[-1][0])#last row, first column

9
7


In [ ]:
#1D array slicing
arr=np.array([10,20,30,40,50])
print(arr[1:4])#1 to 3
print(arr[:3])# starting to 3
print(arr[3:])# 3 to ending
print(arr[::2])#every 2nd element
print("Reverse:",arr[::-1])#Reversing the array

[20 30 40]
[10 20 30]
[40 50]
[10 30 50]
Reverse: [50 40 30 20 10]


In [ ]:
#2D array slicing
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr[0:2,1:3]) # rows 0-1, columns 1-2
print(arr[:,1])#print all rows,column 1
print(arr[1,:])#print all columns,row 1

[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]


Shape manipulation (reshape, flatten, transpose)

In [ ]:
#Reshape
import numpy as np
arr=np.array([2,3,5,9])
print("ORIGINAL ARRAY:",arr)
res=arr.reshape(2,2)
print("RESHAPED ARRAY:\n",res)

ORIGINAL ARRAY: [2 3 5 9]
RESHAPED ARRAY:
 [[2 3]
 [5 9]]


In [ ]:
#Flatten
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6]])
flatarr=arr.flatten()
print("Flatten array is:",flatarr)

Flatten array is: [1 2 3 4 5 6]


In [ ]:
#Transpose
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr_transpose=arr.transpose()
print("Transpose array is:\n",arr_transpose)

Transpose array is:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Math ops (mean, std, sum, dot, matmul).

In [ ]:
#Mean of 1d array
arr=np.array([1,2,3])
print("ORIGINAL ARRAY:",arr)
total_mean=np.mean(arr)
print("Mean:",total_mean)

ORIGINAL ARRAY: [1 2 3]
Mean: 2.0


In [ ]:
#Mean of 2d array
arr=np.array([[1,2,3],
             [4,5,6]])
print("ORIGINAL ARRAY:",arr)
total_mean=np.mean(arr)
print("Mean:",total_mean)
print("Mean of total columns:",np.mean(arr,axis=0))
print("Mean of total rows:",np.mean(arr,axis=1))

ORIGINAL ARRAY: [[1 2 3]
 [4 5 6]]
Mean: 3.5
Mean of total columns: [2.5 3.5 4.5]
Mean of total rows: [2. 5.]


In [ ]:
#Standard deviation
arr=np.array([1,2,3])
print("ORIGINAL ARRAY:",arr)
print("Standard deviation:",np.std(arr))

ORIGINAL ARRAY: [1 2 3]
Standard deviation: 0.816496580927726


In [ ]:
#Sum of 1d array
arr=np.array([1,2,3])
print("ORIGINAL ARRAY:",arr)
sum_value = np.sum(arr)
print("Sum:",sum_value)

ORIGINAL ARRAY: [1 2 3]
Standard deviation: 6


In [ ]:
#Sum of 2d array
arr=np.array([[1,2,3],
              [4,5,6]])
print("ORIGINAL ARRAY\n:",arr)
sum_value = np.sum(arr)
print("Sum:",sum_value)
print("Sum of columns:",np.sum(arr,axis=0))
print("Sum of rows:",np.sum(arr,axis=1))

ORIGINAL ARRAY
: [[1 2 3]
 [4 5 6]]
Sum: 21
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]


In [ ]:
#Dot product of 1d array
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
dot_product=np.dot(arr1,arr2)
print("Dot product:",dot_product)

Dot product: 14


In [ ]:
#Dot product of 1d array
arr1=np.array([[1,2,3],
               [4,5,6],
               [4,3,1]])
arr2=np.array([[8,2,3],
               [2,5,1],
               [2,5,3]])
dot_product=np.dot(arr1,arr2)
print("Dot product:\n",dot_product)

Dot product:
 [[18 27 14]
 [54 63 35]
 [40 28 18]]


In [ ]:
#Matrix multiplication of  array
arr1=np.array([[1,2,3],
               [4,5,6],
               [4,3,1]])
arr2=np.array([[8,2,3],
               [2,5,1],
               [2,5,3]])
mult=np.matmul(arr1,arr2)
print("Matrix multiplication:\n",mult)

Matrix multiplication:
 [[18 27 14]
 [54 63 35]
 [40 28 18]]


Random module (rand, randn, randint, choice).

In [ ]:
#Random (rand())
import numpy as np
r=np.random.rand()
print("Random no:",r)
arr=np.random.rand(5)
print("1D array:",arr)
arr2d=np.random.rand(2,3)
print("2D array:\n",arr2d)

Random no: 0.4516666182932333
1D array: [0.64394998 0.29742351 0.53513435 0.21893727 0.01766028]
2D array:
 [[0.15734567 0.08491472 0.47896731]
 [0.96724818 0.91165147 0.69684855]]


In [ ]:
#randn() – Standard normal distribution
#Syntax: np.random.randn(d0, d1, ..., dn)
r=np.random.rand()
print("Random no:",r)
arr=np.random.randn(5)
print("1D array:",arr)
arr2d=np.random.randn(2,3)
print("2D array:\n",arr2d)

Random no: 0.9678086064463443
1D array: [ 1.52801189  0.37825851 -0.30871098  1.48421824 -0.18326426]
2D array:
 [[ 0.22060737 -0.48565889 -0.04205304]
 [ 0.30690068  1.97606607  0.76422804]]


In [ ]:
#randint() – Random integers
#Syntax: np.random.randint(low, high=None, size=None)
r=np.random.randint(0,10)
print("Random no:",r)
arr=np.random.randint(0,10,size=5)
print("1D array:",arr)
arr2d=np.random.randint(10,50,size=(2,3))
print("2D array:\n",arr2d)

Random no: 6
1D array: [7 8 8 4 5]
2D array:
 [[40 17 38]
 [30 36 22]]


In [ ]:
#choice() – Random selection from an array/list
#Syntax: np.random.choice(a, size=None, replace=True, p=None)
arr=[10,20,30,40]
r=np.random.choice(arr)
print("Random choice:",r)
r=np.random.choice(arr,size=3)
print("3 random choices:",r)
r=np.random.choice(arr,size=3,replace=False)
print("3 unique random choices:",r)
r = np.random.choice(arr, p=[0.1, 0.2, 0.3, 0.4])
print("Weighted random choices:", r)

Random choice: 30
3 random choices: [40 10 10]
3 unique random choices: [30 20 40]
Weighted random choices: 20
